" [ *** ============ STITCHING OR & XOR ============ ***] "
==========================

In [11]:
#pylint:disable=no-member

import cv2
import numpy as np


# =============== [ P A R A M E T E R ]
#=========================================================
pathResultImages = r"Result_Images\\"
heightBEV = 785
widthBEV = 657
# =============== Camera Filename Images
Camera_A_Name = "6.1.BEV-FINAL-SameSize-Camera_A_1.jpg"
Camera_B_Name = "6.1.BEV-FINAL-SameSize-Camera_B_1.jpg"
Camera_C_Name = "6.1.BEV-FINAL-SameSize-Camera_C_1.jpg"
Camera_D_Name = "6.1.BEV-FINAL-SameSize-Camera_D_1.jpg"
print("=> Filename: ", Camera_A_Name,Camera_B_Name,Camera_C_Name,Camera_D_Name)
print()
#=========================================================
# =============== [ P A R A M E T E R ]

# =============== [ F U N C T I O N ]
#=========================================================
def readCamera(cameraName, Camera_Filename):
    img = cv2.imread(Camera_Filename)
    if (cameraName == "D"):
        # Rotate D - No Rotate
        pass
    elif (cameraName == "B"):
        # Camera B - Rotate 90 COUNTERCLOCKWISE
        # img = cv2.rotate(img, cv2.cv2.ROTATE_90_COUNTERCLOCKWISE)
        pass
    elif (cameraName == "C"):
        # Camera C - Rotate 90 CLOCKWISE
        # img = cv2.rotate(img, cv2.cv2.ROTATE_90_CLOCKWISE)
        pass
    elif (cameraName == "A"):
        # Camera A - Rotate 180 
        # img = cv2.rotate(img, cv2.cv2.ROTATE_180)
        pass
    cv2.imshow(Camera_Filename, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    return img
#=========================================================
def writeNewImage(img, pathWriteImg):
    cv2.imwrite(pathWriteImg, img)
#=========================================================
# =============== [ F U N C T I O N ]

# =============== [ M A I N - F U N C T I O N ]
#=========================================================
def main():
    print("==> 1. Size BEV")
    print("Height: ", heightBEV)
    print("Width: ", widthBEV)
    print()

    print("==> 2. Read Camera & Rotate")
    print()
    # ==================== Read Camera & Rotate
    imgCameraA = readCamera("A", Camera_A_Name)
    imgCameraB = readCamera("B", Camera_B_Name)
    imgCameraC = readCamera("C", Camera_C_Name)
    imgCameraD = readCamera("D", Camera_D_Name)

    '''
    # bitwise AND --> intersecting regions
    bitwise_and_Vertical = cv2.bitwise_and(imgCameraA, imgCameraD)
    cv2.imshow('Bitwise AND [imgCameraA,imgCameraD]', bitwise_and_Vertical)
    bitwise_and_Horizontal = cv2.bitwise_and(imgCameraB, imgCameraC)
    cv2.imshow('Bitwise AND [imgCameraB,imgCameraC]', bitwise_and_Horizontal)
    bitwise_and_Full = cv2.bitwise_and(bitwise_and_Vertical, bitwise_and_Horizontal)
    cv2.imshow('Bitwise AND [FULL]', bitwise_and_Full)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    '''
    
    # bitwise OR --> non-intersecting and intersecting regions
    bitwise_or_Vertical = cv2.bitwise_or(imgCameraA, imgCameraD)
    cv2.imshow('Bitwise OR [imgCameraA,imgCameraD]', bitwise_or_Vertical)
    bitwise_or_Horizontal = cv2.bitwise_or(imgCameraB, imgCameraC)
    cv2.imshow('Bitwise OR [imgCameraB, imgCameraC]', bitwise_or_Horizontal)
    bitwise_or_Full = cv2.bitwise_or(bitwise_or_Vertical, bitwise_or_Horizontal)
    cv2.imshow('Bitwise OR [FULL]', bitwise_or_Full)
    print("==> 4. Write new Images")
    print()
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    # ==================== Write new Images
    filenameImage = "1.1.STITCHING-BEV-OR-"
    filenameImage = pathResultImages + filenameImage
    writeNewImage(bitwise_or_Full, filenameImage+Camera_A_Name)

    # bitwise XOR --> non-intersecting regions
    bitwise_xor_Vertical = cv2.bitwise_xor(imgCameraA, imgCameraD)
    cv2.imshow('Bitwise XOR [imgCameraA,imgCameraD]', bitwise_xor_Vertical)
    bitwise_xor_Horizontal = cv2.bitwise_xor(imgCameraB, imgCameraC)
    cv2.imshow('Bitwise XOR [imgCameraB, imgCameraC]', bitwise_xor_Horizontal)
    bitwise_xor_Full = cv2.bitwise_xor(bitwise_xor_Vertical, bitwise_xor_Horizontal)
    cv2.imshow('Bitwise XOR [FULL]', bitwise_xor_Full)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    # ==================== Write new Images
    filenameImage = "1.1.STITCHING-BEV-XOR-"
    filenameImage = pathResultImages + filenameImage
    writeNewImage(bitwise_xor_Full, filenameImage+Camera_A_Name)

    # bitwise NOT
    #bitwise_not = cv2.bitwise_not(imgCameraA)
    #cv2.imshow('imgCameraA NOT', bitwise_not)
    #cv2.waitKey(0)
    #cv2.destroyAllWindows()

#=========================================================
# =============== [ M A I N - F U N C T I O N ]

if __name__ == '__main__':       
    # Calling main() function 
    main()

=> Filename:  6.1.BEV-FINAL-SameSize-Camera_A_1.jpg 6.1.BEV-FINAL-SameSize-Camera_B_1.jpg 6.1.BEV-FINAL-SameSize-Camera_C_1.jpg 6.1.BEV-FINAL-SameSize-Camera_D_1.jpg

==> 1. Size BEV
Height:  706
Width:  1040

==> 2. Read Camera & Rotate

==> 4. Write new Images



" [ *** ============ STITCHING OR ============ ***] "
==========================

In [22]:
#pylint:disable=no-member

import cv2
import numpy as np


# =============== [ P A R A M E T E R ]
#=========================================================
pathResultImages = r"Result_Images\\"
BEV_Name = "1.Rectangle-BEV Camera Show (Crop).jpg"
heightBEV = 706
widthBEV = 1040
# =============== Camera Filename Images
Camera_A_Name = "6.1.BEV-FINAL-SameSize-Camera_A_1.jpg"
Camera_B_Name = "6.1.BEV-FINAL-SameSize-Camera_B_1.jpg"
Camera_C_Name = "6.1.BEV-FINAL-SameSize-Camera_C_1.jpg"
Camera_D_Name = "6.1.BEV-FINAL-SameSize-Camera_D_1.jpg"
print("=> Filename: ", Camera_A_Name,Camera_B_Name,Camera_C_Name,Camera_D_Name)
print()
#=========================================================
# =============== [ P A R A M E T E R ]

# =============== [ F U N C T I O N ]
#=========================================================
def readCamera(cameraName, Camera_Filename):
    img = cv2.imread(Camera_Filename)
    if (cameraName == "A"):
        # Rotate A - No Rotate
        pass
    elif (cameraName == "B"):
        # Camera B - Rotate 90 COUNTERCLOCKWISE
        # img = cv2.rotate(img, cv2.cv2.ROTATE_90_COUNTERCLOCKWISE)
        pass
    elif (cameraName == "C"):
        # Camera C - Rotate 90 CLOCKWISE
        # img = cv2.rotate(img, cv2.cv2.ROTATE_90_CLOCKWISE)
        pass
    elif (cameraName == "D"):
        # Camera D - Rotate 180 
        # img = cv2.rotate(img, cv2.cv2.ROTATE_180)
        pass
    '''
    cv2.imshow(Camera_Filename, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    '''
    return img
#=========================================================
def writeNewImage(img, pathWriteImg):
    cv2.imwrite(pathWriteImg, img)
#=========================================================
# =============== [ F U N C T I O N ]

# =============== [ M A I N - F U N C T I O N ]
#=========================================================
def main():
    print("==> 1. Size BEV")
    print("Height: ", heightBEV)
    print("Width: ", widthBEV)
    print()

    print("==> 2. Read Camera & Rotate")
    print()
    # ==================== Read Camera & Rotate
    imgCameraA = readCamera("A", Camera_A_Name)
    imgCameraB = readCamera("B", Camera_B_Name)
    imgCameraC = readCamera("C", Camera_C_Name)
    imgCameraD = readCamera("D", Camera_D_Name)
    
    # bitwise OR --> non-intersecting and intersecting regions
    bitwise_or_Vertical = cv2.bitwise_or(imgCameraA, imgCameraD)
    cv2.imshow('Bitwise OR [imgCameraA,imgCameraD]', bitwise_or_Vertical)
    bitwise_or_Horizontal = cv2.bitwise_or(imgCameraB, imgCameraC)
    cv2.imshow('Bitwise OR [imgCameraB, imgCameraC]', bitwise_or_Horizontal)
    #=====================================================================================
    img2gray = cv2.cvtColor(bitwise_or_Vertical,cv2.COLOR_BGR2GRAY)
    ret, mask = cv2.threshold(img2gray, 200, 255, cv2.THRESH_BINARY_INV)
    cv2.imshow('mask', mask)
    mask_inv = cv2.bitwise_not(mask)
    #=====================================================================================
    bitwise_or_Full = cv2.bitwise_or(bitwise_or_Vertical, bitwise_or_Horizontal)
    cv2.imshow('Bitwise OR [FULL]', bitwise_or_Full)
    img_add = cv2.add(bitwise_or_Vertical,bitwise_or_Horizontal)
    cv2.imshow('ADD', img_add)
    print("==> 4. Write new Images")
    print()
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    # ==================== Write new Images
    filenameImage = "2.1.STITCHING-BEV-OR-"
    filenameImage = pathResultImages + filenameImage
    writeNewImage(bitwise_or_Full, filenameImage+Camera_A_Name)

#=========================================================
# =============== [ M A I N - F U N C T I O N ]

if __name__ == '__main__':       
    # Calling main() function 
    main()

=> Filename:  6.1.BEV-FINAL-SameSize-Camera_A_1.jpg 6.1.BEV-FINAL-SameSize-Camera_B_1.jpg 6.1.BEV-FINAL-SameSize-Camera_C_1.jpg 6.1.BEV-FINAL-SameSize-Camera_D_1.jpg

==> 1. Size BEV
Height:  706
Width:  1040

==> 2. Read Camera & Rotate

==> 4. Write new Images



" [ *** ============ STITCHING AND & MASKING & ADD ============ ***] "
==========================

In [1]:
#pylint:disable=no-member

import cv2
import numpy as np


# =============== [ P A R A M E T E R ]
#=========================================================
pathResultImages = r"Result_Images\\"
BEV_Name = "1.Rectangle-BEV Camera Show (Crop).jpg"
heightBEV = 785
widthBEV = 657
# =============== Camera Filename Images
Camera_A_Name = "6.1.BEV-FINAL-SameSize-Camera_A_1.jpg"
Camera_B_Name = "6.1.BEV-FINAL-SameSize-Camera_B_1.jpg"
Camera_C_Name = "6.1.BEV-FINAL-SameSize-Camera_C_1.jpg"
Camera_D_Name = "6.1.BEV-FINAL-SameSize-Camera_D_1.jpg"
print("=> Filename: ", Camera_A_Name,Camera_B_Name,Camera_C_Name,Camera_D_Name)
print()
#=========================================================
# =============== [ P A R A M E T E R ]

# =============== [ F U N C T I O N ]
#=========================================================
def readCamera(cameraName, Camera_Filename):
    img = cv2.imread(Camera_Filename)
    if (cameraName == "D"):
        # Rotate D - No Rotate
        pass
    elif (cameraName == "B"):
        # Camera B - Rotate 90 COUNTERCLOCKWISE
        # img = cv2.rotate(img, cv2.cv2.ROTATE_90_COUNTERCLOCKWISE)
        pass
    elif (cameraName == "C"):
        # Camera C - Rotate 90 CLOCKWISE
        # img = cv2.rotate(img, cv2.cv2.ROTATE_90_CLOCKWISE)
        pass
    elif (cameraName == "A"):
        # Camera A - Rotate 180 
        # img = cv2.rotate(img, cv2.cv2.ROTATE_180)
        pass
    '''
    cv2.imshow(Camera_Filename, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    '''
    return img
#=========================================================
def writeNewImage(img, pathWriteImg):
    cv2.imwrite(pathWriteImg, img)
#=========================================================
# =============== [ F U N C T I O N ]

# =============== [ M A I N - F U N C T I O N ]
#=========================================================
def main():
    print("==> 1. Size BEV")
    print("Height: ", heightBEV)
    print("Width: ", widthBEV)
    print()

    print("==> 2. Read Camera & Rotate")
    print()
    # ==================== Read Camera & Rotate
    imgCameraA = readCamera("A", Camera_A_Name)
    imgCameraB = readCamera("B", Camera_B_Name)
    imgCameraC = readCamera("C", Camera_C_Name)
    imgCameraD = readCamera("D", Camera_D_Name)

    # ==================== ADD
    img_add_Ver = cv2.add(imgCameraA,imgCameraD)
    img_add_Hor = cv2.add(imgCameraB,imgCameraC)
    #cv2.imshow('ADD - Vertical', img_add_Ver)
    #cv2.imshow('ADD - Horizontal', img_add_Hor)

    # ==================== MASK - VERTICAL
    img2gray = cv2.cvtColor(img_add_Ver,cv2.COLOR_BGR2GRAY)
    cv2.imshow('img2gray', img2gray)
    ret, mask = cv2.threshold(img2gray, 1, 255, cv2.THRESH_BINARY_INV)
    mask = cv2.GaussianBlur(mask,(3,3),3)
    cv2.imshow('mask', mask)
    # ==================== MASK - HORIZONTAL
    img2grayHorizontal = cv2.cvtColor(img_add_Hor,cv2.COLOR_BGR2GRAY)
    cv2.imshow('img2grayHorizontal', img2grayHorizontal)
    ret, maskHorizontal = cv2.threshold(img2grayHorizontal, 1, 255, cv2.THRESH_BINARY_INV)
    maskHorizontal = cv2.GaussianBlur(maskHorizontal,(3,3),3)
    cv2.imshow('maskHorizontal', maskHorizontal)
    print(mask)
    print(type(mask))

    # ==================== BITWISE AND
    #img_bitwise_and = cv2.bitwise_and(img_add_Ver,img_add_Hor,mask = mask)
    #cv2.imshow('bitwise_and', img_bitwise_and)
    img_add_Hor = cv2.bitwise_and(img_add_Hor,img_add_Hor,mask = mask)
    cv2.imshow('img_add_Hor', img_add_Hor)
    cv2.imshow('img_add_Ver', img_add_Ver)

    # ==================== ADD - FINAL
    imgStitching = cv2.add(img_add_Ver,img_add_Hor)
    cv2.imshow('Stitching - Final ' + Camera_A_Name, imgStitching)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

    print("==> 4. Write new Images")
    print()

    # ==================== Write new Images
    filenameImage = "3.STITCHING-BEV-FINAL-"
    filenameImage = pathResultImages + filenameImage
    writeNewImage(imgStitching, filenameImage+Camera_A_Name)
    
    # ==================== Write Parameter Masking
    cv2.imwrite("_PARAMS_MASKING_VERTICAL_.jpg", mask)
    # ==================== Write Parameter Masking
    cv2.imwrite("_PARAMS_MASKING_HORIZONTAL_.jpg", maskHorizontal)

#=========================================================
# =============== [ M A I N - F U N C T I O N ]

if __name__ == '__main__':       
    # Calling main() function 
    main()

=> Filename:  6.1.BEV-FINAL-SameSize-Camera_A_1.jpg 6.1.BEV-FINAL-SameSize-Camera_B_1.jpg 6.1.BEV-FINAL-SameSize-Camera_C_1.jpg 6.1.BEV-FINAL-SameSize-Camera_D_1.jpg

==> 1. Size BEV
Height:  785
Width:  657

==> 2. Read Camera & Rotate

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>
==> 4. Write new Images



" [ *** ============ FINAL STITCHING ============ ***] "
==========================

In [23]:
import cv2
import numpy as np

# =============== [ P A R A M E T E R ]
#=========================================================
pathResultImages = r"Result_Images\\"
BEV_Name = "1.Rectangle-BEV Camera Show (Crop).jpg"
heightBEV = 785
widthBEV = 657
# =============== Camera Filename Images
Camera_A_Name = "6.1.BEV-FINAL-SameSize-Camera_A_1.jpg"
Camera_B_Name = "6.1.BEV-FINAL-SameSize-Camera_B_1.jpg"
Camera_C_Name = "6.1.BEV-FINAL-SameSize-Camera_C_1.jpg"
Camera_D_Name = "6.1.BEV-FINAL-SameSize-Camera_D_1.jpg"
print("=> Filename: ", Camera_A_Name,Camera_B_Name,Camera_C_Name,Camera_D_Name)
print()
# =============== Masking Parameter 
Parameter_Masking_NameX = r"_PARAMS_MASKING_HORIZONTAL_.jpg"
Parameter_Masking_NameY = r"_PARAMS_MASKING_VERTICAL_.jpg"
#=========================================================
# =============== [ P A R A M E T E R ]

# =============== [ F U N C T I O N ]
#=========================================================
def readImageReal(cameraName, Camera_Filename):
    if cameraName == "Mask":
        img = cv2.imread(Camera_Filename, 0)
    else:
        img = cv2.imread(Camera_Filename)
    '''
    cv2.imshow(Camera_Filename, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    '''
    return img
def stitchCamera(imgA,imgB,imgC,imgD, imgMaskX, imgMaskY):
    cv2.imshow('imgMaskX', imgMaskX)
    cv2.imshow('imgMaskY', imgMaskY)

    # ==================== ADD
    img_add_Ver = cv2.add(imgA,imgD)
    img_add_Hor = cv2.add(imgB,imgC)

    # ==================== BITWISE AND & MASKING [VERTICAL]
    img_add_Ver = cv2.bitwise_and(img_add_Ver,img_add_Ver,mask = imgMaskX)
    # ERASE THE ERROR WITH LINE (BLACK DOTS)
    color = (0,0,0)
    thickness = 10
    img_add_Ver = cv2.line(img_add_Ver,(407,290),(592,0),color,thickness)
    img_add_Ver = cv2.line(img_add_Ver,(227,290),(62,0),color,thickness)
    img_add_Ver = cv2.line(img_add_Ver,(235,519),(84,785),color,thickness)
    img_add_Ver = cv2.line(img_add_Ver,(389,519),(508,785),color,thickness)
    # ==================== BITWISE AND & MASKING [HORIZONTAL]
    #img_add_Hor = cv2.bitwise_and(img_add_Hor,img_add_Hor,mask = imgMaskY)
    cv2.imshow('img_add_Hor', img_add_Hor)
    cv2.imshow('img_add_Ver', img_add_Ver)

    # ==================== ADD - FINAL
    imgStitching = cv2.add(img_add_Ver,img_add_Hor)
    cv2.imshow('Stitching - Final ', imgStitching)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    return imgStitching
#=========================================================
def writeNewImage(img, pathWriteImg):
    cv2.imwrite(pathWriteImg, img)
#=========================================================
# =============== [ F U N C T I O N ]

# =============== [ M A I N - F U N C T I O N ]
#=========================================================
def main():
    print("==> 1. Size BEV")
    print("Height: ", heightBEV)
    print("Width: ", widthBEV)
    print()

    print("==> 2. Read Camera")
    print()
    # ==================== Read Camera
    imgCameraA = readImageReal("A", Camera_A_Name)
    imgCameraB = readImageReal("B", Camera_B_Name)
    imgCameraC = readImageReal("C", Camera_C_Name)
    imgCameraD = readImageReal("D", Camera_D_Name)
    # ==================== Read Masking 
    imgMaskingX = readImageReal("Mask", Parameter_Masking_NameX)
    imgMaskingY = readImageReal("Mask", Parameter_Masking_NameY)

    print("==> 3. Stitching Camera A-B-C-D")
    print()
    # ==================== Stitching Camera A-B-C-D
    imgStitch = stitchCamera(imgCameraA,imgCameraB,imgCameraC,imgCameraD, imgMaskingX,imgMaskingY)

    print("==> 4. Write new Images")
    print()
    # ==================== Write new Images
    filenameImage = "4.STITCHING-BEV-FINAL-"
    filenameImage = pathResultImages + filenameImage
    writeNewImage(imgStitch, filenameImage+Camera_A_Name)
#=========================================================
# =============== [ M A I N - F U N C T I O N ]

if __name__ == '__main__':       
    # Calling main() function 
    main()

=> Filename:  6.1.BEV-FINAL-SameSize-Camera_A_1.jpg 6.1.BEV-FINAL-SameSize-Camera_B_1.jpg 6.1.BEV-FINAL-SameSize-Camera_C_1.jpg 6.1.BEV-FINAL-SameSize-Camera_D_1.jpg

==> 1. Size BEV
Height:  785
Width:  657

==> 2. Read Camera

==> 3. Stitching Camera A-B-C-D

==> 4. Write new Images

